'use client';

import { useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import { 
  Shield, 
  FileText, 
  CheckCircle, 
  Download, 
  Copy, 
  ArrowRight, 
  Plus, 
  Star,
  Activity,
  Lock
} from 'lucide-react';
import { jsPDF } from 'jspdf';

const STRIPE_PAYMENT_LINK = "https://buy.stripe.com/test_5kQ9AMaPw3toajS4M80VO00";

export default function PolicyFlowAI() {
  const [step, setStep] = useState<'landing' | 'generator'>('landing');
  const [formData, setFormData] = useState({
    clinicType: '',
    state: '',
    policyType: '',
    notes: ''
  });
  const [policyText, setPolicyText] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generationsCount, setGenerationsCount] = useState(0);
  const resultRef = useRef<HTMLDivElement>(null);

  // Load generation count from localStorage
  useEffect(() => {
    const savedCount = localStorage.getItem('policy_generations_count');
    if (savedCount) {
      setGenerationsCount(parseInt(savedCount, 10));
    }
  }, []);

  const incrementGenerations = () => {
    const newCount = generationsCount + 1;
    setGenerationsCount(newCount);
    localStorage.setItem('policy_generations_count', newCount.toString());
  };

  const hasReachedLimit = generationsCount >= 1;

  // Auto-scroll when policyText is updated
  useEffect(() => {
    if (policyText && resultRef.current) {
      resultRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [policyText]);

  const handleStart = () => {
    setStep('generator');
    setError(null);
    setPolicyText(null);
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (hasReachedLimit && !policyText) return;
    
    setIsGenerating(true);
    setError(null);
    setPolicyText(null);
    
    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate policy');
      }

      if (!data.policy) {
        throw new Error('API returned successfully but no "policy" field was found in the response.');
      }

      setPolicyText(data.policy);
      incrementGenerations();
    } catch (err: any) {
      console.error('Frontend Error:', err);
      setError(err.message || 'An unexpected error occurred.');
    } finally {
      setIsGenerating(false);
    }
  };

  const copyToClipboard = () => {
    if (!policyText) return;
    navigator.clipboard.writeText(policyText);
    alert('Policy copied to clipboard!');
  };

  const downloadPDF = () => {
    if (!policyText) return;
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text("PolicyFlow AI", 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 27);
    
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(20, 32, 190, 32);
    
    // Title & Info
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);
    doc.text(formData.policyType || "Clinic Policy", 20, 45);
    
    doc.setFontSize(11);
    doc.text(`${formData.clinicType} - ${formData.state}`, 20, 52);
    
    // Body Text
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59); // slate-800
    const splitText = doc.splitTextToSize(policyText, 170);
    doc.text(splitText, 20, 65);
    
    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184); // slate-400
      doc.text("CONFIDENTIAL - Generated by PolicyFlow AI. This document should be reviewed by legal counsel.", 20, 285);
    }

    doc.save(`${formData.policyType.replace(/\s+/g, '_') || 'Policy'}.pdf`);
  };

  return (
    <main className="min-h-screen bg-slate-50">
      <nav className="bg-white border-b border-slate-200 py-4 px-6 sticky top-0 z-50">
        <div className="max-w-6xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => setStep('landing')}>
            <Activity className="text-blue-600 w-8 h-8" />
            <span className="font-bold text-xl tracking-tight text-slate-900">PolicyFlow AI</span>
          </div>
          <div className="flex gap-6 items-center">
            <a href="#pricing" className="text-slate-600 hover:text-blue-600 font-medium">Pricing</a>
            <button onClick={handleStart} className="bg-blue-600 text-white px-5 py-2 rounded-lg font-semibold hover:bg-blue-700 transition-colors">
              Get Started
            </button>
          </div>
        </div>
      </nav>

      {step === 'landing' && (
        <div className="animate-in fade-in duration-500">
          <section className="py-20 px-6 text-center">
            <div className="max-w-4xl mx-auto">
              <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 px-4 py-1.5 rounded-full text-sm font-medium mb-6">
                <Star className="w-4 h-4 fill-blue-600" />
                <span>Trusted by 500+ clinics nationwide</span>
              </div>
              <h1 className="text-5xl md:text-6xl font-extrabold text-slate-900 mb-6 tracking-tight">
                Generate audit-ready clinic policies and SOPs in minutes using AI.
              </h1>
              <p className="text-xl text-slate-600 mb-10 max-w-2xl mx-auto">
                Built specifically for telehealth, wellness, weight loss, and med spa clinics. Save hours of manual work and stay compliant.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <button onClick={handleStart} className="bg-blue-600 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-blue-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-blue-200">
                  Generate Your First Policy <ArrowRight className="w-5 h-5" />
                </button>
                <a href="#samples" className="bg-white text-slate-700 border border-slate-200 px-8 py-4 rounded-xl font-bold text-lg hover:bg-slate-50 transition-all text-center">
                  View Samples
                </a>
              </div>
            </div>
          </section>

          <section className="py-20 bg-white border-y border-slate-100 px-6 grid md:grid-cols-3 gap-12 max-w-6xl mx-auto">
            {[
              { icon: Shield, title: "Audit-Ready", desc: "Trained on clinical standards and state-specific healthcare regulations." },
              { icon: FileText, title: "Specialized Context", desc: "Tailored for modern clinics like Med Spas and Telehealth providers." },
              { icon: CheckCircle, title: "Instant Export", desc: "Download as PDF or copy directly to your operations manual." }
            ].map((f, i) => (
              <div key={i} className="flex flex-col gap-4">
                <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600"><f.icon className="w-6 h-6" /></div>
                <h3 className="text-xl font-bold text-slate-900">{f.title}</h3>
                <p className="text-slate-600">{f.desc}</p>
              </div>
            ))}
          </section>

          <section id="samples" className="py-24 px-6 bg-slate-50">
            <div className="max-w-6xl mx-auto text-center mb-16">
              <h2 className="text-4xl font-bold text-slate-900 mb-4">Sample Policies</h2>
              <div className="grid md:grid-cols-3 gap-8 text-left mt-12">
                {[
                  { title: "HIPAA Privacy Policy", preview: "Outlines safeguards implemented to protect PHI...", type: "Compliance" },
                  { title: "Telehealth Consent Policy", preview: "Establishes protocol for virtual visit consent...", type: "Patient Care" },
                  { title: "Medication Refill SOP", preview: "Standard procedure for managing refill requests...", type: "Operations" }
                ].map((s, i) => (
                  <div key={i} className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                    <span className="inline-block px-3 py-1 bg-blue-50 text-blue-600 text-xs font-bold rounded-full mb-4 uppercase">{s.type}</span>
                    <h3 className="text-xl font-bold text-slate-900 mb-3">{s.title}</h3>
                    <p className="text-slate-600 text-sm italic mb-6">"{s.preview}"</p>
                    <button onClick={handleStart} className="text-blue-600 font-bold text-sm flex items-center gap-1">Generate similar <ArrowRight className="w-4 h-4" /></button>
                  </div>
                ))}
              </div>
            </div>
          </section>

          <section id="pricing" className="py-24 px-6 text-center">
            <h2 className="text-4xl font-bold text-slate-900 mb-16">Simple, transparent pricing.</h2>
            <div className="max-w-md mx-auto bg-white border-2 border-blue-600 rounded-3xl p-8 shadow-xl relative overflow-hidden text-left">
              <div className="absolute top-0 right-0 bg-blue-600 text-white px-4 py-1 text-sm font-bold uppercase transform translate-x-12 translate-y-6 rotate-45">Popular</div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">PolicyFlow AI Professional</h3>
              <div className="flex items-baseline gap-1 mb-8"><span className="text-5xl font-extrabold text-slate-900">$149</span><span className="text-slate-500">/month</span></div>
              <ul className="space-y-4 mb-10 text-slate-700">
                {["Unlimited AI Policy Generation", "State-Specific Logic", "Download as PDF", "Audit Checklists"].map((f, i) => (
                  <li key={i} className="flex items-center gap-3"><CheckCircle className="w-5 h-5 text-blue-600" />{f}</li>
                ))}
              </ul>
              <a href={STRIPE_PAYMENT_LINK} target="_blank" rel="noopener noreferrer" className="w-full bg-blue-600 text-white py-4 rounded-xl font-bold text-lg text-center block hover:bg-blue-700">Get Started Now</a>
            </div>
          </section>
        </div>
      )}

      {step === 'generator' && (
        <div className="py-20 px-6 max-w-4xl mx-auto">
          <button onClick={() => setStep('landing')} className="text-slate-500 mb-8 flex items-center gap-1 font-medium">← Back to Home</button>
          <div className="bg-white rounded-3xl p-8 md:p-10 shadow-xl border border-slate-100 mb-8">
            <h2 className="text-3xl font-bold text-slate-900 mb-8">Generate Policy</h2>
            <form onSubmit={handleGenerate} className="space-y-6">
              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-700">Clinic Type</label>
                  <select required className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3" value={formData.clinicType} onChange={(e) => setFormData({...formData, clinicType: e.target.value})}>
                    <option value="">Select type...</option>
                    <option value="Telehealth">Telehealth</option>
                    <option value="Wellness Clinic">Wellness Clinic</option>
                    <option value="Weight Loss Clinic">Weight Loss Clinic</option>
                    <option value="Med Spa">Med Spa</option>
                  </select>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-semibold text-slate-700">State</label>
                  <select required className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3" value={formData.state} onChange={(e) => setFormData({...formData, state: e.target.value})}>
                    <option value="">Select state...</option>
                    <option value="California">California</option>
                    <option value="Florida">Florida</option>
                    <option value="Texas">Texas</option>
                    <option value="New York">New York</option>
                    <option value="Arizona">Arizona</option>
                    <option value="Other">Other (USA)</option>
                  </select>
                </div>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-slate-700">Policy/SOP Type</label>
                <input required placeholder="e.g. HIPAA Compliance" className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3" value={formData.policyType} onChange={(e) => setFormData({...formData, policyType: e.target.value})} />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-slate-700">Additional Notes (Optional)</label>
                <textarea placeholder="Any specific requirements?" className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 min-h-[120px]" value={formData.notes} onChange={(e) => setFormData({...formData, notes: e.target.value})}></textarea>
              </div>
              {error && <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm font-bold">Error: {error}</div>}
              
              {hasReachedLimit && !policyText ? (
                <div className="space-y-4">
                  <div className="p-6 bg-amber-50 border border-amber-200 rounded-2xl text-center">
                    <p className="text-amber-800 font-bold mb-1">Free preview limit reached.</p>
                    <p className="text-amber-700 text-sm">Upgrade to continue generating policies.</p>
                  </div>
                  <a href={STRIPE_PAYMENT_LINK} target="_blank" rel="noopener noreferrer" className="w-full bg-blue-600 text-white py-4 rounded-xl font-bold text-lg hover:bg-blue-700 transition-all flex items-center justify-center gap-2 shadow-lg shadow-blue-200">
                    Upgrade to Professional <ArrowRight className="w-5 h-5" />
                  </a>
                </div>
              ) : (
                <button type="submit" disabled={isGenerating} className="w-full bg-blue-600 text-white py-4 rounded-xl font-bold text-lg hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-3">
                  {isGenerating ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : <><Plus className="w-5 h-5" /> Generate Policy</>}
                </button>
              )}
            </form>
          </div>

          <div className="max-w-2xl mx-auto text-center mb-12">
            <p className="text-xs md:text-sm text-slate-500 leading-relaxed italic">
              “PolicyFlow AI generates operational policy drafts for business use. It does not provide legal advice. Users should review and customize outputs for their specific practice, state, and compliance requirements.”
            </p>
          </div>

          {policyText && (
            <div ref={resultRef} className="animate-in fade-in slide-in-from-bottom-4 duration-700">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
                <h3 className="text-2xl font-bold text-slate-900">Generated Policy</h3>
                <div className="flex gap-3">
                  <button onClick={copyToClipboard} className="bg-white text-slate-700 border border-slate-200 px-4 py-2 rounded-lg font-semibold hover:bg-slate-50 flex items-center gap-2 text-sm"><Copy className="w-4 h-4" /> Copy</button>
                  
                  <div className="relative group">
                    <button 
                      disabled={hasReachedLimit}
                      onClick={downloadPDF} 
                      className={`bg-white text-slate-700 border border-slate-200 px-4 py-2 rounded-lg font-semibold flex items-center gap-2 text-sm transition-all ${hasReachedLimit ? 'opacity-50 grayscale cursor-not-allowed' : 'hover:bg-slate-50'}`}
                    >
                      <Download className="w-4 h-4" /> PDF
                    </button>
                    {hasReachedLimit && (
                      <div className="absolute bottom-full mb-2 left-1/2 -translate-x-1/2 w-48 p-2 bg-slate-900 text-white text-[10px] rounded shadow-xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none text-center">
                        Available with PolicyFlow AI Professional
                      </div>
                    )}
                  </div>

                  <a href={STRIPE_PAYMENT_LINK} target="_blank" rel="noopener noreferrer" className="bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-blue-700 flex items-center gap-2 text-sm">Upgrade</a>
                </div>
              </div>
              <div className="bg-white rounded-2xl p-8 md:p-12 shadow-lg border border-slate-100 font-serif leading-relaxed text-slate-800 whitespace-pre-wrap">
                {policyText}
              </div>

              <div className="mt-8 flex justify-center">
                <div className="relative group">
                  <button 
                    disabled={hasReachedLimit}
                    onClick={downloadPDF}
                    className={`px-10 py-4 rounded-xl font-bold text-lg transition-all flex items-center gap-3 shadow-lg ${hasReachedLimit ? 'bg-slate-100 text-slate-400 cursor-not-allowed' : 'bg-blue-600 text-white hover:bg-blue-700 shadow-blue-100'}`}
                  >
                    {hasReachedLimit && <Lock className="w-5 h-5 text-slate-400" />}
                    <Download className="w-5 h-5" /> Download as PDF
                  </button>
                  {hasReachedLimit && (
                    <div className="absolute bottom-full mb-3 left-1/2 -translate-x-1/2 w-64 p-3 bg-slate-900 text-white text-xs rounded-lg shadow-2xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none text-center z-10">
                      <p className="font-bold mb-1">Premium Feature</p>
                      <p className="text-slate-400">PDF exports are available with PolicyFlow AI Professional.</p>
                    </div>
                  )}
                </div>
              </div>
              
              <div className="mt-8 text-center">
                {hasReachedLimit ? (
                  <div className="flex flex-col items-center gap-2">
                    <p className="text-slate-500 text-sm font-medium">Free preview limit reached.</p>
                    <a href={STRIPE_PAYMENT_LINK} className="text-blue-600 font-bold hover:underline flex items-center gap-1">Upgrade to generate unlimited policies <ArrowRight className="w-4 h-4" /></a>
                  </div>
                ) : (
                  <button onClick={() => { setPolicyText(null); window.scrollTo({ top: 0, behavior: 'smooth' }); }} className="text-slate-500 hover:text-slate-700 font-medium text-sm text-center">Clear and Generate Another</button>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      <footer className="bg-slate-900 text-slate-400 py-12 px-6 mt-20">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8 text-sm">
          <div className="flex items-center gap-2"><Activity className="text-blue-500 w-6 h-6" /><span className="font-bold text-white">PolicyFlow AI</span></div>
          <div className="flex gap-8">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms of Service</Link>
            <Link href="/contact" className="hover:text-white transition-colors">Contact</Link>
          </div>
          <p>© 2026 PolicyFlow AI. All rights reserved.</p>
        </div>
      </footer>
    </main>
  );
}
