import { Activity, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | PolicyFlow AI',
  description: 'Read the terms and conditions for using the PolicyFlow AI clinical policy generator.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-50 py-20 px-6">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="flex items-center gap-2 text-slate-500 hover:text-blue-600 transition-colors mb-12 font-medium">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        
        <div className="bg-white rounded-3xl p-10 md:p-16 shadow-xl border border-slate-100">
          <div className="flex items-center gap-2 mb-8">
            <Activity className="text-blue-600 w-8 h-8" />
            <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
          </div>
          
          <div className="prose prose-slate max-w-none space-y-6 text-slate-600 leading-relaxed">
            <p className="text-sm font-semibold uppercase tracking-wider text-slate-400">Last Updated: May 15, 2026</p>
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">1. Use of Service</h2>
              <p>PolicyFlow AI provides a platform for generating clinic policy drafts. By using our service, you agree to comply with all applicable laws and regulations.</p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">2. Not Legal Advice</h2>
              <p>The content generated by PolicyFlow AI is for informational and business operational purposes only. It does not constitute legal advice. We strongly recommend that all generated documentation be reviewed by professional legal counsel before being adopted by your clinic.</p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">3. Limitation of Liability</h2>
              <p>PolicyFlow AI is not liable for any regulatory non-compliance, legal issues, or clinical errors resulting from the use of its generated templates. Users assume full responsibility for the accuracy and legality of the policies they implement.</p>
            </section>
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3">4. Payments</h2>
              <p>Professional plan subscriptions are billed monthly. Cancellations take effect at the end of the current billing cycle. No refunds are provided for partial months.</p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
